name: Release Draft
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*'  # Push events to matching tags
jobs:
  release-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all tags for branch
 
      - name: Create Release Draft
        id: create_release_draft
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            Changes since last release:
            ${{ steps.changelog.outputs.changelog }}
      - name: Get Changelog
        id: changelog
        uses: easingthemes/action-git-changelog@v1.2.0
        with:
          from: ${{ steps.create_release_draft.outputs.previous_tag }}
          to: ${{ github.ref }}
          template: '{{#commits}}{{{message}}}{{/commits}}'